[package]
name = "oasis-core-runtime"
version = "0.0.0"
authors = ["Oasis Protocol Foundation <info@oasisprotocol.org>"]
edition = "2018"

[dependencies]
cbor = { version = "0.2.1", package = "oasis-cbor" }

# Third party.
log = "0.4"
slog = "2.7.0"
slog-json = "2.4.0"
slog-scope = "4.4.0"
slog-stdlog = "4.1.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.71"
lazy_static = "1.3.0"
crossbeam = "0.8.1"
byteorder = "1.4.3"
anyhow = "1.0"
thiserror = "1.0"
sgx-isa = { version = "0.3.3", features = ["sgxstd"] }
bincode = "1.3.3"
snow = "0.8.0"
percent-encoding = "2.1.0"
chrono = "0.4.19"
base64 = "0.13.0"
rustc-hex = "2.0.1"
rand = "0.7.3"
futures = "0.3.17"
tokio = { version = "1", features = ["rt", "sync"] }
tendermint = { git = "https://github.com/informalsystems/tendermint-rs", branch = "master" }
tendermint-proto = { git = "https://github.com/informalsystems/tendermint-rs", branch = "master" }
tendermint-light-client = { git = "https://github.com/informalsystems/tendermint-rs", branch = "master", default-features = false }
tendermint-rpc = { git = "https://github.com/informalsystems/tendermint-rs", branch = "master", default-features = false }
io-context = "0.2.0"
curve25519-dalek = "3.2.0"
x25519-dalek = "1.1.0"
ed25519-dalek = "1.0.1"
deoxysii = "0.2.2"
tiny-keccak = { version = "2.0.2", features = ["sha3"] }
sp800-185 = "0.2.0"
zeroize = "1.4"
intrusive-collections = "0.9.2"
sha2 = "0.9.8"
hmac = "0.11.0"
honggfuzz = "0.5.54"
arbitrary = { version = "1.0.2", features = ["derive"] }
num-bigint = "0.4"
num-traits = "0.2.14"
bech32 = "0.8.1"
impl-trait-for-tuples = "0.2.1"
x509-parser = "0.11.0"
oid-registry = "0.1.5"
rsa = "0.5.0"
base64-serde = "0.6.1"
lru = "0.7.0"

[target.'cfg(not(target_env = "sgx"))'.dependencies.tokio]
version = "1"
features = ["full"]

[dev-dependencies]
# For storage interoperability tests only.
# Temporary import till https://github.com/apoelstra/rust-jsonrpc/pull/42 is merged.
jsonrpc = { git = "https://github.com/darosior/rust-jsonrpc", branch = "moar_transports", features = ["simple_uds"] }
tempfile = "3.2.0"

[[bin]]
name = "fuzz-mkvs-proof"
path = "fuzz/mkvs_proof.rs"

[[bin]]
name = "fuzz-mkvs-node"
path = "fuzz/mkvs_node.rs"
